config/routes.rb
Papyrus::Application.routes.draw do

  root :to => 'welcome#index'

  get '/sign_up', :to => "accounts#new", :as => :sign_up
  post '/accounts', :to => "accounts#create", :as => :accounts

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
end

app/controllers/application_controller.rb
require 'warden'

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_account
    if user_signed_in?
      @current_account ||= begin
                             account_id = request.env['warden'].user(:scope => :account)
                             Account.find(account_id)
                           end
    end
  end

  def current_user
    if user_signed_in?
      @current_user ||= begin
                             user_id = request.env['warden'].user(:scope => :user)
                             User.find(user_id)
                           end
    end
  end

  def user_signed_in?
    request.env['warden'].authenticated?(:user)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Papyrus</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% flash.each do |k,v| %>
      <div class='flash <%= k %>'><%= v %></div>
    <% end %>

    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>
    <% end%>

  <%= yield %>

</body>
</html>

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml

= link_to "Account Sign Up", sign_up_path